version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: healem-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-healem_admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-CHANGE_THIS_SECURE_PASSWORD_IN_PRODUCTION}
      MONGO_INITDB_DATABASE: healem
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - healem-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: healem-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME:-healem_admin}:${MONGO_ROOT_PASSWORD:-CHANGE_THIS_SECURE_PASSWORD_IN_PRODUCTION}@mongodb:27017/healem?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-CHANGE_THIS_JWT_SECRET_TO_RANDOM_64_CHAR_STRING}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - healem-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: healem-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - healem-network
    environment:
      REACT_APP_API_URL: http://localhost:5000/api

volumes:
  mongodb_data:

networks:
  healem-network:
    driver: bridge